/*
 * CIDAView.java
 */

package cs.cirg.cida;

import cs.cirg.cida.analysis.SynopsisTableModel;
import cs.cirg.cida.table.IOBridgeTableModel;
import org.jdesktop.application.Action;
import org.jdesktop.application.ResourceMap;
import org.jdesktop.application.SingleFrameApplication;
import org.jdesktop.application.FrameView;
import org.jdesktop.application.TaskMonitor;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.Timer;
import javax.swing.Icon;
import javax.swing.JDialog;
import javax.swing.JFrame;
import org.jfree.chart.ChartPanel;

/**
 * The application's main frame.
 */
public class CIDAView extends FrameView {

    public CIDAView(SingleFrameApplication app) {
        super(app);

        initComponents();

        // status bar initialization - message timeout, idle icon and busy animation, etc
        ResourceMap resourceMap = getResourceMap();
        int messageTimeout = resourceMap.getInteger("StatusBar.messageTimeout");
        messageTimer = new Timer(messageTimeout, new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                statusMessageLabel.setText("");
            }
        });
        messageTimer.setRepeats(false);
        int busyAnimationRate = resourceMap.getInteger("StatusBar.busyAnimationRate");
        for (int i = 0; i < busyIcons.length; i++) {
            busyIcons[i] = resourceMap.getIcon("StatusBar.busyIcons[" + i + "]");
        }
        busyIconTimer = new Timer(busyAnimationRate, new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                busyIconIndex = (busyIconIndex + 1) % busyIcons.length;
                statusAnimationLabel.setIcon(busyIcons[busyIconIndex]);
            }
        });
        idleIcon = resourceMap.getIcon("StatusBar.idleIcon");
        statusAnimationLabel.setIcon(idleIcon);
        progressBar.setVisible(false);

        // connecting action tasks to status bar via TaskMonitor
        TaskMonitor taskMonitor = new TaskMonitor(getApplication().getContext());
        taskMonitor.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                String propertyName = evt.getPropertyName();
                if ("started".equals(propertyName)) {
                    if (!busyIconTimer.isRunning()) {
                        statusAnimationLabel.setIcon(busyIcons[0]);
                        busyIconIndex = 0;
                        busyIconTimer.start();
                    }
                    progressBar.setVisible(true);
                    progressBar.setIndeterminate(true);
                } else if ("done".equals(propertyName)) {
                    busyIconTimer.stop();
                    statusAnimationLabel.setIcon(idleIcon);
                    progressBar.setVisible(false);
                    progressBar.setValue(0);
                } else if ("message".equals(propertyName)) {
                    String text = (String)(evt.getNewValue());
                    statusMessageLabel.setText((text == null) ? "" : text);
                    messageTimer.restart();
                } else if ("progress".equals(propertyName)) {
                    int value = (Integer)(evt.getNewValue());
                    progressBar.setVisible(true);
                    progressBar.setIndeterminate(false);
                    progressBar.setValue(value);
                }
            }
        });
    }

    @Action
    public void showAboutBox() {
        if (aboutBox == null) {
            JFrame mainFrame = CIDAApplication.getApplication().getMainFrame();
            aboutBox = new CIDAAboutBox(mainFrame);
            aboutBox.setLocationRelativeTo(mainFrame);
        }
        CIDAApplication.getApplication().show(aboutBox);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        testPanel = new javax.swing.JTabbedPane();
        homePanel = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        experimentsLabel = new javax.swing.JLabel();
        loadExperimentButton = new javax.swing.JButton();
        experimentsComboBox = new javax.swing.JComboBox();
        jCheckBox1 = new javax.swing.JCheckBox();
        addToTestButton = new javax.swing.JButton();
        variablesLabel = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        addToAnalysisButton = new javax.swing.JButton();
        addToSynopsisButton = new javax.swing.JButton();
        addAllRowsCheckBox = new javax.swing.JCheckBox();
        addAllVariablesButton = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        rawPanel = new javax.swing.JPanel();
        rawPanelToolbar = new javax.swing.JToolBar();
        exportDataButton = new javax.swing.JButton();
        rawScrollPane = new javax.swing.JScrollPane();
        rawTable = new javax.swing.JTable();
        analysisPanel = new javax.swing.JPanel();
        analysisToolbar = new javax.swing.JToolBar();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        analysisScrollPane = new javax.swing.JScrollPane();
        rawTable1 = new javax.swing.JTable();
        chartHomePanel = new javax.swing.JPanel();
        chartToolbar = new javax.swing.JToolBar();
        jToggleButton1 = new javax.swing.JToggleButton();
        lineSeriesComboBox = new javax.swing.JComboBox();
        seriesColorButton = new javax.swing.JButton();
        seriesNameButton = new javax.swing.JButton();
        exportPNGButton = new javax.swing.JButton();
        exportEPSButton = new javax.swing.JButton();
        chartScrollPane = new javax.swing.JScrollPane();
        chartPanel = new ChartPanel(null, true, true, false, true, true);
        jPanel1 = new javax.swing.JPanel();
        testToolbar = new javax.swing.JToolBar();
        jLabel1 = new javax.swing.JLabel();
        variablesTestComboBox = new javax.swing.JComboBox();
        mannWhitneyUTestButton = new javax.swing.JButton();
        testExperimentsScrollPane = new javax.swing.JScrollPane();
        testExperimentsTable = new javax.swing.JTable();
        testResultsScrollPane = new javax.swing.JScrollPane();
        testResultsTable = new javax.swing.JTable();
        menuBar = new javax.swing.JMenuBar();
        javax.swing.JMenu fileMenu = new javax.swing.JMenu();
        javax.swing.JMenuItem exitMenuItem = new javax.swing.JMenuItem();
        javax.swing.JMenu helpMenu = new javax.swing.JMenu();
        javax.swing.JMenuItem aboutMenuItem = new javax.swing.JMenuItem();
        statusPanel = new javax.swing.JPanel();
        javax.swing.JSeparator statusPanelSeparator = new javax.swing.JSeparator();
        statusMessageLabel = new javax.swing.JLabel();
        statusAnimationLabel = new javax.swing.JLabel();
        progressBar = new javax.swing.JProgressBar();

        mainPanel.setName("mainPanel"); // NOI18N
        mainPanel.setPreferredSize(new java.awt.Dimension(1280, 1024));

        testPanel.setName("testPanel"); // NOI18N

        homePanel.setName("homePanel"); // NOI18N

        jSeparator1.setName("jSeparator1"); // NOI18N

        jSeparator2.setName("jSeparator2"); // NOI18N

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        jTable1.setAutoCreateRowSorter(true);
        jTable1.setModel(new SynopsisTableModel());
        jTable1.setColumnSelectionAllowed(true);
        jTable1.setName("jTable1"); // NOI18N
        jScrollPane1.setViewportView(jTable1);
        jTable1.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(cs.cirg.cida.CIDAApplication.class).getContext().getResourceMap(CIDAView.class);
        experimentsLabel.setText(resourceMap.getString("experimentsLabel.text")); // NOI18N
        experimentsLabel.setName("experimentsLabel"); // NOI18N

        loadExperimentButton.setText(resourceMap.getString("loadExperimentButton.text")); // NOI18N
        loadExperimentButton.setMaximumSize(new java.awt.Dimension(110, 29));
        loadExperimentButton.setMinimumSize(new java.awt.Dimension(110, 29));
        loadExperimentButton.setName("loadExperimentButton"); // NOI18N
        loadExperimentButton.setPreferredSize(new java.awt.Dimension(110, 29));

        experimentsComboBox.setModel(new javax.swing.DefaultComboBoxModel());
        experimentsComboBox.setName("experimentsComboBox"); // NOI18N

        jCheckBox1.setText(resourceMap.getString("jCheckBox1.text")); // NOI18N
        jCheckBox1.setName("jCheckBox1"); // NOI18N

        addToTestButton.setText(resourceMap.getString("addToTestButton.text")); // NOI18N
        addToTestButton.setMaximumSize(new java.awt.Dimension(110, 29));
        addToTestButton.setMinimumSize(new java.awt.Dimension(110, 29));
        addToTestButton.setName("addToTestButton"); // NOI18N
        addToTestButton.setPreferredSize(new java.awt.Dimension(110, 29));

        variablesLabel.setText(resourceMap.getString("variablesLabel.text")); // NOI18N
        variablesLabel.setName("variablesLabel"); // NOI18N

        jComboBox1.setName("jComboBox1"); // NOI18N

        addToAnalysisButton.setText(resourceMap.getString("addToAnalysisButton.text")); // NOI18N
        addToAnalysisButton.setName("addToAnalysisButton"); // NOI18N

        addToSynopsisButton.setText(resourceMap.getString("addToSynopsisButton.text")); // NOI18N
        addToSynopsisButton.setName("addToSynopsisButton"); // NOI18N

        addAllRowsCheckBox.setSelected(true);
        addAllRowsCheckBox.setText(resourceMap.getString("addAllRowsCheckBox.text")); // NOI18N
        addAllRowsCheckBox.setName("addAllRowsCheckBox"); // NOI18N

        addAllVariablesButton.setText(resourceMap.getString("addAllVariablesButton.text")); // NOI18N
        addAllVariablesButton.setName("addAllVariablesButton"); // NOI18N

        jButton1.setText(resourceMap.getString("jButton1.text")); // NOI18N
        jButton1.setName("jButton1"); // NOI18N

        org.jdesktop.layout.GroupLayout homePanelLayout = new org.jdesktop.layout.GroupLayout(homePanel);
        homePanel.setLayout(homePanelLayout);
        homePanelLayout.setHorizontalGroup(
            homePanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(homePanelLayout.createSequentialGroup()
                .addContainerGap()
                .add(homePanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jSeparator1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 1044, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jSeparator2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 1044, Short.MAX_VALUE)
                    .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 1044, Short.MAX_VALUE)
                    .add(homePanelLayout.createSequentialGroup()
                        .add(variablesLabel)
                        .add(18, 18, 18)
                        .add(jComboBox1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 350, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(homePanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                            .add(addToSynopsisButton, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .add(addAllVariablesButton, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .add(jButton1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, addToAnalysisButton, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(addAllRowsCheckBox))
                    .add(homePanelLayout.createSequentialGroup()
                        .add(experimentsLabel)
                        .add(62, 62, 62)
                        .add(experimentsComboBox, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 348, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(homePanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, addToTestButton, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, loadExperimentButton, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jCheckBox1)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 192, Short.MAX_VALUE)))
                .addContainerGap())
        );
        homePanelLayout.setVerticalGroup(
            homePanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(homePanelLayout.createSequentialGroup()
                .addContainerGap()
                .add(homePanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(experimentsLabel)
                    .add(homePanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                        .add(loadExperimentButton, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(jCheckBox1)
                        .add(experimentsComboBox, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(addToTestButton, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(139, 139, 139)
                .add(jSeparator1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 10, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(homePanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(variablesLabel)
                    .add(homePanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                        .add(jComboBox1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(addToAnalysisButton)
                        .add(addAllRowsCheckBox)))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(addToSynopsisButton)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(addAllVariablesButton)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jButton1)
                .add(51, 51, 51)
                .add(jSeparator2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 10, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 471, Short.MAX_VALUE)
                .addContainerGap())
        );

        testPanel.addTab(resourceMap.getString("homePanel.TabConstraints.tabTitle"), homePanel); // NOI18N

        rawPanel.setName("rawPanel"); // NOI18N

        rawPanelToolbar.setRollover(true);
        rawPanelToolbar.setName("rawPanelToolbar"); // NOI18N

        exportDataButton.setText(resourceMap.getString("exportDataButton.text")); // NOI18N
        exportDataButton.setFocusable(false);
        exportDataButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        exportDataButton.setName("exportDataButton"); // NOI18N
        exportDataButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        rawPanelToolbar.add(exportDataButton);

        rawScrollPane.setName("rawScrollPane"); // NOI18N

        rawTable.setAutoCreateRowSorter(true);
        rawTable.setModel(new IOBridgeTableModel());
        rawTable.setColumnSelectionAllowed(true);
        rawTable.setName("rawTable"); // NOI18N
        rawScrollPane.setViewportView(rawTable);
        rawTable.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);

        org.jdesktop.layout.GroupLayout rawPanelLayout = new org.jdesktop.layout.GroupLayout(rawPanel);
        rawPanel.setLayout(rawPanelLayout);
        rawPanelLayout.setHorizontalGroup(
            rawPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(rawPanelToolbar, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 1056, Short.MAX_VALUE)
            .add(rawScrollPane, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 1056, Short.MAX_VALUE)
        );
        rawPanelLayout.setVerticalGroup(
            rawPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(rawPanelLayout.createSequentialGroup()
                .add(rawPanelToolbar, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 25, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(rawScrollPane, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 896, Short.MAX_VALUE)
                .addContainerGap())
        );

        testPanel.addTab(resourceMap.getString("rawPanel.TabConstraints.tabTitle"), rawPanel); // NOI18N

        analysisPanel.setName("analysisPanel"); // NOI18N

        analysisToolbar.setRollover(true);
        analysisToolbar.setName("analysisToolbar"); // NOI18N

        jButton2.setText(resourceMap.getString("jButton2.text")); // NOI18N
        jButton2.setFocusable(false);
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton2.setName("jButton2"); // NOI18N
        jButton2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        analysisToolbar.add(jButton2);

        jButton4.setText(resourceMap.getString("jButton4.text")); // NOI18N
        jButton4.setFocusable(false);
        jButton4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton4.setName("jButton4"); // NOI18N
        jButton4.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        analysisToolbar.add(jButton4);

        jButton3.setText(resourceMap.getString("jButton3.text")); // NOI18N
        jButton3.setFocusable(false);
        jButton3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton3.setName("jButton3"); // NOI18N
        jButton3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        analysisToolbar.add(jButton3);

        analysisScrollPane.setName("analysisScrollPane"); // NOI18N

        rawTable1.setAutoCreateRowSorter(true);
        rawTable1.setModel(new IOBridgeTableModel());
        rawTable1.setName("rawTable1"); // NOI18N
        analysisScrollPane.setViewportView(rawTable1);
        rawTable1.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);

        org.jdesktop.layout.GroupLayout analysisPanelLayout = new org.jdesktop.layout.GroupLayout(analysisPanel);
        analysisPanel.setLayout(analysisPanelLayout);
        analysisPanelLayout.setHorizontalGroup(
            analysisPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(analysisToolbar, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 1056, Short.MAX_VALUE)
            .add(analysisScrollPane, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 1056, Short.MAX_VALUE)
        );
        analysisPanelLayout.setVerticalGroup(
            analysisPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(analysisPanelLayout.createSequentialGroup()
                .add(analysisToolbar, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 25, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(analysisScrollPane, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 896, Short.MAX_VALUE)
                .addContainerGap())
        );

        testPanel.addTab(resourceMap.getString("analysisPanel.TabConstraints.tabTitle"), analysisPanel); // NOI18N

        chartHomePanel.setName("chartHomePanel"); // NOI18N

        chartToolbar.setRollover(true);
        chartToolbar.setName("chartToolbar"); // NOI18N

        jToggleButton1.setText(resourceMap.getString("jToggleButton1.text")); // NOI18N
        jToggleButton1.setFocusable(false);
        jToggleButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jToggleButton1.setName("jToggleButton1"); // NOI18N
        jToggleButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        chartToolbar.add(jToggleButton1);

        lineSeriesComboBox.setModel(new javax.swing.DefaultComboBoxModel());
        lineSeriesComboBox.setName("lineSeriesComboBox"); // NOI18N
        chartToolbar.add(lineSeriesComboBox);

        seriesColorButton.setText(resourceMap.getString("seriesColorButton.text")); // NOI18N
        seriesColorButton.setFocusable(false);
        seriesColorButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        seriesColorButton.setName("seriesColorButton"); // NOI18N
        seriesColorButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        chartToolbar.add(seriesColorButton);

        seriesNameButton.setText(resourceMap.getString("seriesNameButton.text")); // NOI18N
        seriesNameButton.setFocusable(false);
        seriesNameButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        seriesNameButton.setName("seriesNameButton"); // NOI18N
        seriesNameButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        chartToolbar.add(seriesNameButton);

        exportPNGButton.setText(resourceMap.getString("exportPNGButton.text")); // NOI18N
        exportPNGButton.setFocusable(false);
        exportPNGButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        exportPNGButton.setName("exportPNGButton"); // NOI18N
        exportPNGButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        chartToolbar.add(exportPNGButton);

        exportEPSButton.setText(resourceMap.getString("exportEPSButton.text")); // NOI18N
        exportEPSButton.setFocusable(false);
        exportEPSButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        exportEPSButton.setName("exportEPSButton"); // NOI18N
        exportEPSButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        chartToolbar.add(exportEPSButton);

        chartScrollPane.setName("chartScrollPane"); // NOI18N

        chartPanel.setName("chartPanel"); // NOI18N

        org.jdesktop.layout.GroupLayout chartPanelLayout = new org.jdesktop.layout.GroupLayout(chartPanel);
        chartPanel.setLayout(chartPanelLayout);
        chartPanelLayout.setHorizontalGroup(
            chartPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 1036, Short.MAX_VALUE)
        );
        chartPanelLayout.setVerticalGroup(
            chartPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 928, Short.MAX_VALUE)
        );

        chartScrollPane.setViewportView(chartPanel);

        org.jdesktop.layout.GroupLayout chartHomePanelLayout = new org.jdesktop.layout.GroupLayout(chartHomePanel);
        chartHomePanel.setLayout(chartHomePanelLayout);
        chartHomePanelLayout.setHorizontalGroup(
            chartHomePanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(chartToolbar, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 1056, Short.MAX_VALUE)
            .add(chartScrollPane, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 1056, Short.MAX_VALUE)
        );
        chartHomePanelLayout.setVerticalGroup(
            chartHomePanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(chartHomePanelLayout.createSequentialGroup()
                .add(chartToolbar, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 25, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(chartScrollPane, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 908, Short.MAX_VALUE))
        );

        testPanel.addTab(resourceMap.getString("chartHomePanel.TabConstraints.tabTitle"), chartHomePanel); // NOI18N

        jPanel1.setName("jPanel1"); // NOI18N

        testToolbar.setRollover(true);
        testToolbar.setName("testToolbar"); // NOI18N

        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N
        testToolbar.add(jLabel1);

        variablesTestComboBox.setModel(new javax.swing.DefaultComboBoxModel());
        variablesTestComboBox.setName("variablesTestComboBox"); // NOI18N
        testToolbar.add(variablesTestComboBox);

        mannWhitneyUTestButton.setText(resourceMap.getString("mannWhitneyUTestButton.text")); // NOI18N
        mannWhitneyUTestButton.setFocusable(false);
        mannWhitneyUTestButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        mannWhitneyUTestButton.setName("mannWhitneyUTestButton"); // NOI18N
        mannWhitneyUTestButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        testToolbar.add(mannWhitneyUTestButton);

        testExperimentsScrollPane.setName("testExperimentsScrollPane"); // NOI18N

        testExperimentsTable.setAutoCreateRowSorter(true);
        testExperimentsTable.setModel(new SynopsisTableModel());
        testExperimentsTable.setColumnSelectionAllowed(true);
        testExperimentsTable.setName("testExperimentsTable"); // NOI18N
        testExperimentsScrollPane.setViewportView(testExperimentsTable);
        testExperimentsTable.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);

        testResultsScrollPane.setName("testResultsScrollPane"); // NOI18N

        testResultsTable.setAutoCreateRowSorter(true);
        testResultsTable.setModel(new SynopsisTableModel());
        testResultsTable.setName("testResultsTable"); // NOI18N
        testResultsScrollPane.setViewportView(testResultsTable);
        testResultsTable.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(testToolbar, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 1056, Short.MAX_VALUE)
            .add(testExperimentsScrollPane, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 1056, Short.MAX_VALUE)
            .add(testResultsScrollPane, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 1056, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .add(testToolbar, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 25, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(testExperimentsScrollPane, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 390, Short.MAX_VALUE)
                .add(128, 128, 128)
                .add(testResultsScrollPane, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 390, Short.MAX_VALUE))
        );

        testPanel.addTab(resourceMap.getString("jPanel1.TabConstraints.tabTitle"), jPanel1); // NOI18N

        org.jdesktop.layout.GroupLayout mainPanelLayout = new org.jdesktop.layout.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(testPanel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 1060, Short.MAX_VALUE)
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(testPanel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 970, Short.MAX_VALUE)
        );

        menuBar.setName("menuBar"); // NOI18N

        fileMenu.setText(resourceMap.getString("fileMenu.text")); // NOI18N
        fileMenu.setName("fileMenu"); // NOI18N

        javax.swing.ActionMap actionMap = org.jdesktop.application.Application.getInstance(cs.cirg.cida.CIDAApplication.class).getContext().getActionMap(CIDAView.class, this);
        exitMenuItem.setAction(actionMap.get("quit")); // NOI18N
        exitMenuItem.setName("exitMenuItem"); // NOI18N
        fileMenu.add(exitMenuItem);

        menuBar.add(fileMenu);

        helpMenu.setText(resourceMap.getString("helpMenu.text")); // NOI18N
        helpMenu.setName("helpMenu"); // NOI18N

        aboutMenuItem.setAction(actionMap.get("showAboutBox")); // NOI18N
        aboutMenuItem.setName("aboutMenuItem"); // NOI18N
        helpMenu.add(aboutMenuItem);

        menuBar.add(helpMenu);

        statusPanel.setName("statusPanel"); // NOI18N

        statusPanelSeparator.setName("statusPanelSeparator"); // NOI18N

        statusMessageLabel.setName("statusMessageLabel"); // NOI18N

        statusAnimationLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        statusAnimationLabel.setName("statusAnimationLabel"); // NOI18N

        progressBar.setName("progressBar"); // NOI18N

        org.jdesktop.layout.GroupLayout statusPanelLayout = new org.jdesktop.layout.GroupLayout(statusPanel);
        statusPanel.setLayout(statusPanelLayout);
        statusPanelLayout.setHorizontalGroup(
            statusPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(statusPanelSeparator, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 1060, Short.MAX_VALUE)
            .add(statusPanelLayout.createSequentialGroup()
                .addContainerGap()
                .add(statusMessageLabel)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 876, Short.MAX_VALUE)
                .add(progressBar, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(statusAnimationLabel)
                .addContainerGap())
        );
        statusPanelLayout.setVerticalGroup(
            statusPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(statusPanelLayout.createSequentialGroup()
                .add(statusPanelSeparator, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(statusPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(statusMessageLabel)
                    .add(statusAnimationLabel)
                    .add(progressBar, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(3, 3, 3))
        );

        setComponent(mainPanel);
        setMenuBar(menuBar);
        setStatusBar(statusPanel);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox addAllRowsCheckBox;
    private javax.swing.JButton addAllVariablesButton;
    private javax.swing.JButton addToAnalysisButton;
    private javax.swing.JButton addToSynopsisButton;
    private javax.swing.JButton addToTestButton;
    private javax.swing.JPanel analysisPanel;
    private javax.swing.JScrollPane analysisScrollPane;
    private javax.swing.JToolBar analysisToolbar;
    private javax.swing.JPanel chartHomePanel;
    private javax.swing.JPanel chartPanel;
    private javax.swing.JScrollPane chartScrollPane;
    private javax.swing.JToolBar chartToolbar;
    private javax.swing.JComboBox experimentsComboBox;
    private javax.swing.JLabel experimentsLabel;
    private javax.swing.JButton exportDataButton;
    private javax.swing.JButton exportEPSButton;
    private javax.swing.JButton exportPNGButton;
    private javax.swing.JPanel homePanel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTable jTable1;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JComboBox lineSeriesComboBox;
    private javax.swing.JButton loadExperimentButton;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JButton mannWhitneyUTestButton;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JProgressBar progressBar;
    private javax.swing.JPanel rawPanel;
    private javax.swing.JToolBar rawPanelToolbar;
    private javax.swing.JScrollPane rawScrollPane;
    private javax.swing.JTable rawTable;
    private javax.swing.JTable rawTable1;
    private javax.swing.JButton seriesColorButton;
    private javax.swing.JButton seriesNameButton;
    private javax.swing.JLabel statusAnimationLabel;
    private javax.swing.JLabel statusMessageLabel;
    private javax.swing.JPanel statusPanel;
    private javax.swing.JScrollPane testExperimentsScrollPane;
    private javax.swing.JTable testExperimentsTable;
    private javax.swing.JTabbedPane testPanel;
    private javax.swing.JScrollPane testResultsScrollPane;
    private javax.swing.JTable testResultsTable;
    private javax.swing.JToolBar testToolbar;
    private javax.swing.JLabel variablesLabel;
    private javax.swing.JComboBox variablesTestComboBox;
    // End of variables declaration//GEN-END:variables

    private final Timer messageTimer;
    private final Timer busyIconTimer;
    private final Icon idleIcon;
    private final Icon[] busyIcons = new Icon[15];
    private int busyIconIndex = 0;

    private JDialog aboutBox;
}
